SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE IF EXISTS TB_CM01M01;
DROP TABLE IF EXISTS TB_CM02M01;
DROP TABLE IF EXISTS TB_CM03M01;
DROP TABLE IF EXISTS TB_CM04M01;
DROP TABLE IF EXISTS TB_CM05M01;




/* Create Tables */

CREATE TABLE TB_CM01M01
(
	AUTH_ID varchar(50) NOT NULL,
	AUTH_NM varchar(100),
	EXPL varchar(2000),
	AUTH_ROLE varchar(500),
	CREAT_ID varchar(20) NOT NULL,
	CREAT_PGM varchar(30) NOT NULL,
	CREAT_DTTM timestamp NOT NULL,
	UDT_ID varchar(20),
	UPD_PGM varchar(30),
	UDT_DTTM timestamp,
	CONSTRAINT TB_CM01M01_PK PRIMARY KEY (AUTH_ID)
);


CREATE TABLE TB_CM02M01
(
	ROLE_ID varchar(20) NOT NULL,
	ROLE_NM varchar(100),
	ROLE_TYPE varchar(20),
	ROLE_PTTRN varchar(200),
	EXPL varchar(2000),
	ROLE_MENU varchar(500),
	SORT_NO int,
	CREAT_ID varchar(20) NOT NULL,
	CREAT_PGM varchar(30) NOT NULL,
	CREAT_DTTM timestamp NOT NULL,
	UDT_ID varchar(20),
	UPD_PGM varchar(30),
	UDT_DTTM timestamp,
	CONSTRAINT TB_CM02M01_PK PRIMARY KEY (ROLE_ID)
);


CREATE TABLE TB_CM03M01
(
	MENU_ID varchar(20) NOT NULL,
	MENU_NM varchar(100),
	UP_MENU_ID varchar(20),
	MENU_URL varchar(500),
	MENU_TYPE varchar(20),
	SORT_NO int,
	USE_YN char,
	CREAT_ID varchar(20) NOT NULL,
	CREAT_PGM varchar(30) NOT NULL,
	CREAT_DTTM timestamp NOT NULL,
	UDT_ID varchar(20),
	UPD_PGM varchar(30),
	UDT_DTTM timestamp,
	CONSTRAINT TB_CM03M01_PK PRIMARY KEY (MENU_ID)
);


CREATE TABLE TB_CM04M01
(
	DEPT_ID varchar(20) NOT NULL,
	DEPT_NM varchar(100),
	UP_DEPT_ID varchar(20),
	DEPT_TYPE varchar(50),
	SORT_NO int,
	USE_YN char,
	CREAT_ID varchar(20) NOT NULL,
	CREAT_PGM varchar(30) NOT NULL,
	CREAT_DTTM timestamp NOT NULL,
	UDT_ID varchar(20),
	UPD_PGM varchar(30),
	UDT_DTTM timestamp,
	CONSTRAINT TB_CM04M01_PK PRIMARY KEY (DEPT_ID)
);


CREATE TABLE TB_CM05M01
(
	CODE_ID varchar(20) NOT NULL,
	CODE_NM varchar(100),
	CODE_KIND varchar(20),
	CODE_DESC varchar(500),
	SORT_NO int,
	USE_YN char,
	CREAT_ID varchar(20) NOT NULL,
	CREAT_PGM varchar(30) NOT NULL,
	CREAT_DTTM timestamp NOT NULL,
	UDT_ID varchar(20),
	UPD_PGM varchar(30),
	UDT_DTTM timestamp,
	CONSTRAINT TB_CM05M01_PK PRIMARY KEY (CODE_ID)
);

