CREATE OR REPLACE TRIGGER TB_BM02D02_History
AFTER INSERT OR UPDATE OR DELETE 	-- 행이 추가되거나 값이 변경되었을 때
ON TB_BM02D02 						-- 재고마스터(TB_BM02D02)
FOR EACH ROW 						-- 모든 변경건에 대해 트리거 실행
--담보내역(TB_BM02D02) 변동시
--담보이력(TB_BM02H01) 생성
DECLARE 
    -- 사용할 변수선언
    to_SEQ BINARY_INTEGER :=0;
BEGIN
	SELECT TB_BM02H02_SQ01.NEXTVAL into to_SEQ FROM DUAL  ;
	
	IF inserting THEN
		INSERT INTO TB_BM02H02
		(
			TRST_NO, PROC_DTTM, CHG_CD, PLDG_SN, CLNT_CD, CO_CD, SELPCH_CD, PLDG_DIV_CD, PLDG_AMT, PLDG_RCOGN_RATE, EXPRTN_DT, SETUP_DT, PLDG_RMK, USE_YN, CREAT_ID, CREAT_PGM, CREAT_DTTM, UDT_ID, UDT_PGM, UDT_DTTM
		)
		VALUES (
 			 to_SEQ
			, sysdate			--변동일자
			,'CHG01'			--변동사유(신규)
			,:NEW.PLDG_SN
			,:NEW.CLNT_CD
			,:NEW.CO_CD
			,:NEW.SELPCH_CD
			,:NEW.PLDG_DIV_CD
			,:NEW.PLDG_AMT
			,:NEW.PLDG_RCOGN_RATE
			,:NEW.EXPRTN_DT
			,:NEW.SETUP_DT
			,:NEW.PLDG_RMK
			,:NEW.USE_YN
			,:NEW.CREAT_ID
			,:NEW.CREAT_PGM
			,:NEW.CREAT_DTTM
			,:NEW.UDT_ID
			,:NEW.UDT_PGM
			,:NEW.UDT_DTTM
									
		);

	ELSIF updating THEN
		
		INSERT INTO TB_BM02H02
		(
			TRST_NO, PROC_DTTM, CHG_CD, PLDG_SN, CLNT_CD, CO_CD, SELPCH_CD, PLDG_DIV_CD, PLDG_AMT, PLDG_RCOGN_RATE, EXPRTN_DT, SETUP_DT, PLDG_RMK, USE_YN, CREAT_ID, CREAT_PGM, CREAT_DTTM, UDT_ID, UDT_PGM, UDT_DTTM
		)
 		VALUES (
 			 to_SEQ
			, sysdate			--변동일자
			,'CHG02'			--변동사유(수정)
			,:NEW.PLDG_SN
			,:NEW.CLNT_CD
			,:NEW.CO_CD
			,:NEW.SELPCH_CD
			,:NEW.PLDG_DIV_CD
			,:NEW.PLDG_AMT
			,:NEW.PLDG_RCOGN_RATE
			,:NEW.EXPRTN_DT
			,:NEW.SETUP_DT
			,:NEW.PLDG_RMK
			,:NEW.USE_YN
			,:NEW.CREAT_ID
			,:NEW.CREAT_PGM
			,:NEW.CREAT_DTTM
			,:NEW.UDT_ID
			,:NEW.UDT_PGM
			,:NEW.UDT_DTTM
		);
		
	ELSIF deleting THEN
	
		INSERT INTO TB_BM02H02
		(
			TRST_NO, PROC_DTTM, CHG_CD, PLDG_SN, CLNT_CD, CO_CD, SELPCH_CD, PLDG_DIV_CD, PLDG_AMT, PLDG_RCOGN_RATE, EXPRTN_DT, SETUP_DT, PLDG_RMK, USE_YN, CREAT_ID, CREAT_PGM, CREAT_DTTM, UDT_ID, UDT_PGM, UDT_DTTM
		)
 		VALUES (
			 to_SEQ
			, sysdate			--변동일자
			,'CHG03'			--변동사유(삭제)
			,:OLD.PLDG_SN
			,:OLD.CLNT_CD
			,:OLD.CO_CD
			,:OLD.SELPCH_CD
			,:OLD.PLDG_DIV_CD
			,:OLD.PLDG_AMT
			,:OLD.PLDG_RCOGN_RATE
			,:OLD.EXPRTN_DT
			,:OLD.SETUP_DT
			,:OLD.PLDG_RMK
			,:OLD.USE_YN
			,:OLD.CREAT_ID
			,:OLD.CREAT_PGM
			,:OLD.CREAT_DTTM
			,:OLD.UDT_ID
			,:OLD.UDT_PGM
			,:OLD.UDT_DTTM
		);
	END IF;
END;