CREATE OR REPLACE TRIGGER TB_SM01M01_History
AFTER INSERT OR UPDATE OR DELETE 	-- 행이 추가되거나 값이 변경되었을 때
ON TB_SM01M01 						-- 재고마스터(TB_SM01M01)
FOR EACH ROW 						-- 모든 변경건에 대해 트리거 실행
--재고마스터(TB_SM01M01)  변동시
--재고마스터이력(TB_SM01H01) 생성
DECLARE 
    -- 사용할 변수선언
    to_SEQ BINARY_INTEGER :=0;
BEGIN
	SELECT TB_SM01H01_SQ01.NEXTVAL into to_SEQ FROM DUAL  ;
	
	IF inserting THEN
		INSERT INTO TB_SM01H01
		(
			TRST_NO, STOK_SEQ, CO_CD, WH_CD, OWNER_CD, CLNT_CD, TYP_CD, MAKR_CD, PRJCT_CD, PRDT_CD, PRDT_SIZE, PRDT_SPEC
			, PRDT_LEN, IMP_YN, PROC_DTTM, CHG_CD, CHG_QTY, STOCK_QTY, STOCK_UPR, STOCK_AMT, STD_UPR, PCHS_UPR, SELL_UPR
			, SELL_LAST_DT, PROPRT_STOCK_QTY, ODR_QTY, STOCK_CHG_CD
			, ETC_FIELD1, ETC_FIELD2, ETC_FIELD3, CREAT_ID, CREAT_PGM, CREAT_DTTM, UDT_ID, UDT_PGM, UDT_DTTM	
		)
 		VALUES (
 			to_SEQ
			, :NEW.STOK_SEQ
			, :NEW.CO_CD
			, :NEW.WH_CD
			, :NEW.OWNER_CD
			, :NEW.CLNT_CD
			, :NEW.TYP_CD
			, :NEW.MAKR_CD
			, :NEW.PRJCT_CD
			, :NEW.PRDT_CD
			, :NEW.PRDT_SIZE
			, :NEW.PRDT_SPEC
			, :NEW.PRDT_LEN
			, :NEW.IMP_YN
			, sysdate			--재고변동일자
			, 'CHG01'			--재고변동사유
			, :NEW.STOCK_QTY	--재고변동수량
			, :NEW.STOCK_QTY
			, :NEW.STOCK_UPR
			, :NEW.STOCK_AMT
			, :NEW.STD_UPR
			, :NEW.PCHS_UPR
			, :NEW.SELL_UPR
			, :NEW.SELL_LAST_DT
			, :NEW.PROPRT_STOCK_QTY
			, :NEW.ODR_QTY
			, :NEW.STOCK_CHG_CD
			, :NEW.ETC_FIELD1
			, :NEW.ETC_FIELD2
			, :NEW.ETC_FIELD3
			, :NEW.CREAT_ID
			, :NEW.CREAT_PGM
			, :NEW.CREAT_DTTM
			, :NEW.UDT_ID
			, :NEW.UDT_PGM
			, :NEW.UDT_DTTM							
	 );

	ELSIF updating THEN
		INSERT INTO TB_SM01H01
		(
			TRST_NO, STOK_SEQ, CO_CD, WH_CD, OWNER_CD, CLNT_CD, TYP_CD, MAKR_CD, PRJCT_CD, PRDT_CD, PRDT_SIZE, PRDT_SPEC
			, PRDT_LEN, IMP_YN, PROC_DTTM, CHG_CD, CHG_QTY, STOCK_QTY, STOCK_UPR, STOCK_AMT, STD_UPR, PCHS_UPR, SELL_UPR
			, SELL_LAST_DT, PROPRT_STOCK_QTY, ODR_QTY, STOCK_CHG_CD
			, ETC_FIELD1, ETC_FIELD2, ETC_FIELD3, CREAT_ID, CREAT_PGM, CREAT_DTTM, UDT_ID, UDT_PGM, UDT_DTTM	
		)
 		VALUES (
 			to_SEQ
			, :NEW.STOK_SEQ
			, :NEW.CO_CD
			, :NEW.WH_CD
			, :NEW.OWNER_CD
			, :NEW.CLNT_CD
			, :NEW.TYP_CD
			, :NEW.MAKR_CD
			, :NEW.PRJCT_CD
			, :NEW.PRDT_CD
			, :NEW.PRDT_SIZE
			, :NEW.PRDT_SPEC
			, :NEW.PRDT_LEN
			, :NEW.IMP_YN
			, sysdate							--재고변동일자
			, 'CHG02'							--재고변동사유
			, :NEW.STOCK_QTY - :OLD.STOCK_QTY	--재고변동수량
			, :NEW.STOCK_QTY
			, :NEW.STOCK_UPR
			, :NEW.STOCK_AMT
			, :NEW.STD_UPR
			, :NEW.PCHS_UPR
			, :NEW.SELL_UPR
			, :NEW.SELL_LAST_DT
			, :NEW.PROPRT_STOCK_QTY
			, :NEW.ODR_QTY
			, :NEW.STOCK_CHG_CD
			, :NEW.ETC_FIELD1
			, :NEW.ETC_FIELD2
			, :NEW.ETC_FIELD3
			, :NEW.CREAT_ID
			, :NEW.CREAT_PGM
			, :NEW.CREAT_DTTM
			, :NEW.UDT_ID
			, :NEW.UDT_PGM
			, :NEW.UDT_DTTM							
	 );
               
	ELSIF deleting THEN
		INSERT INTO TB_SM01H01
		(
			TRST_NO, STOK_SEQ, CO_CD, WH_CD, OWNER_CD, CLNT_CD, TYP_CD, MAKR_CD, PRJCT_CD, PRDT_CD, PRDT_SIZE, PRDT_SPEC
			, PRDT_LEN, IMP_YN, PROC_DTTM, CHG_CD, CHG_QTY, STOCK_QTY, STOCK_UPR, STOCK_AMT, STD_UPR, PCHS_UPR, SELL_UPR
			, SELL_LAST_DT, PROPRT_STOCK_QTY, ODR_QTY, STOCK_CHG_CD
			, ETC_FIELD1, ETC_FIELD2, ETC_FIELD3, CREAT_ID, CREAT_PGM, CREAT_DTTM, UDT_ID, UDT_PGM, UDT_DTTM	
		)
 		VALUES (
			to_SEQ
			, :OLD.STOK_SEQ
			, :OLD.CO_CD
			, :OLD.WH_CD
			, :OLD.OWNER_CD
			, :OLD.CLNT_CD
			, :OLD.TYP_CD
			, :OLD.MAKR_CD
			, :OLD.PRJCT_CD
			, :OLD.PRDT_CD
			, :OLD.PRDT_SIZE
			, :OLD.PRDT_SPEC
			, :OLD.PRDT_LEN
			, :OLD.IMP_YN
			, sysdate				--재고변동일자
			, 'CHG03'				--재고변동사유
			, :OLD.STOCK_QTY * -1	--재고변동수량
			, :OLD.STOCK_QTY
			, :OLD.STOCK_UPR
			, :OLD.STOCK_AMT
			, :OLD.STD_UPR
			, :OLD.PCHS_UPR
			, :OLD.SELL_UPR
			, :OLD.SELL_LAST_DT
			, :OLD.PROPRT_STOCK_QTY
			, :OLD.ODR_QTY
			, :OLD.STOCK_CHG_CD
			, :OLD.ETC_FIELD1
			, :OLD.ETC_FIELD2
			, :OLD.ETC_FIELD3
			, :OLD.CREAT_ID
			, :OLD.CREAT_PGM
			, :OLD.CREAT_DTTM
			, :OLD.UDT_ID
			, :OLD.UDT_PGM
			, :OLD.UDT_DTTM							
	 );
	END IF;
END;