server:
  port: 8081
spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://49.50.166.245:3306/biz?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: P@ssw0rd
  mvc:    static-path-pattern: /static/**   
mybatis:
  type-aliases-package: com.dksys.biz
sapdks:
  host: 172.31.2.166
  sysnr: 00
  lang: KO
  client: 100
  user: NRPGWUSR
  passwd: 123456