server:
  port: 80
spring:
  autoconfigure:    exclude: org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration, org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
  jpa:    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource1:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    jdbc-url: jdbc:log4jdbc:tibero://61.97.190.240:8629/tibero
    username: goldmoon
    password: goldmoon
  datasource2:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    jdbc-url: jdbc:log4jdbc:mysql://61.97.190.240:3306/ggmsteel?characterEncoding=UTF-8&serverTimezone=UTC
    username: goldmoon
    password: GGs123!@#  
  mvc:
    static-path-pattern: /static/**  servlet:    multipart:      enabled: true
      location: C:/Temp
      max-file-size: 100MB      max-request-size: 100MB       
mybatis:
  type-aliases-package: com.dksys.biz
sap:
  dkshost: 172.31.2.166
  dkssysnr: 00
  dkslang: KO
  dksclient: 100
  dksuser: NRPGWUSR
  dkspasswd: 123456