server:
  port: 8081
spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://49.50.166.245:3306/biz?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: P@ssw0rd
  mvc:    static-path-pattern: /static/**   
mybatis:
  type-aliases-package: com.dksys.biz
sap:
  dkshost: 172.31.2.166
  dkssysnr: 00
  dkslang: KO
  dksclient: 100
  dksuser: NRPGWUSR
  dkspasswd: 123456