server:
  port: 80
spring:
  autoconfigure:
    exclude: 
     - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
     - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
     - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
     - org.springframework.boot.autoconfigure.data.web.SpringDataWebAutoConfiguration
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    jdbc-url: jdbc:log4jdbc:tibero:thin:@61.97.190.240:8629:tibero
    username: goldmoon_dev
    password: gold_dev01
  mvc:
    static-path-pattern: /static/**
  servlet:
    multipart:
      enabled: true
      location: C:/Temp
      max-file-size: 100MB
      max-request-size: 100MB       
mybatis:
  type-aliases-package: com.dksys.biz