SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE IF EXISTS CHAT_MESSAGE;
DROP TABLE IF EXISTS CHAT_ROOM;
DROP TABLE IF EXISTS CHAT_ROOM_JOIN;




/* Create Tables */

CREATE TABLE CHAT_MESSAGE
(
	MESSAGE_ID varchar(100) NOT NULL,
	MESSAGE varchar(4000),
	MESSAGE_TIME timestamp,
	USER_ID varchar(100),
	ROOM_ID varchar(100),
	PRIMARY KEY (MESSAGE_ID)
);


CREATE TABLE CHAT_ROOM
(
	ROOM_ID varchar(100) NOT NULL,
	PRIMARY KEY (ROOM_ID)
);


CREATE TABLE CHAT_ROOM_JOIN
(
	JOIN_ID varchar(100) NOT NULL,
	USER_ID varchar(100),
	ROOM_ID varchar(100),
	PRIMARY KEY (JOIN_ID)
);



